@extends('layouts.general')

@section('meta-description', 'The issue of online privacy is extremely crucial for Reconnaissance Technologies which is committed to safeguarding the information provided by its members and other visitors logging on to its Web site.')
@section('meta-keywords', 'Privacy Policy, Privacy Statement')
@section('robots', 'index, follow')
@section('og-title', 'Privacy Policy - Reconnaissance Technologies | Web and Mobile App Development Company')
@section('og-sitename', 'Reconnaissance Technologies')
@section('og-url', "{{ route('about-us') }}")
@section('og-description', 'The issue of online privacy is extremely crucial for Reconnaissance Technologies which is committed to safeguarding the information provided by its members and other visitors logging on to its Web site.')
@section('og-image', "{{ asset('assets/img/logo-dark.png') }}")
@section('title', 'Privacy Policy - Reconnaissance Technologies | Web and Mobile App Development Company')

@section('custom-styles')
@endsection

@section('content')
<main class="w-full">
    <!-- Hero Section -->
    <section class="bg-gradient-to-tr from-violet-200 to-slate-700 px-16">
        <div class="w-full pt-32 pb-8">
            <h1 class="w-full text-xl text-center lg:text-4xl font-bold mt-2 mb-2">
                Privacy Policy Statement
            </h1>
        </div>
    </section>
    <!-- End of Hero Section -->

    <!-- Privacy Policy Statement Section -->
    <section class="px-16 bg-white dark:text-white dark:bg-gray-800 flex justify-between">
        <div class="w-full py-6">
            <div class="w-full py-8 p-6">
                <p class="pb-6">
                    Reconnaissance Technologies Nigeria Limited ("Reconnaissance Technologies," "we," "us," or "our") is committed to protecting your privacy.
                    This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our website and services.
                    This Privacy Policy applies to our website (www.reconnaissancetechnologies.com) and subscription for regular IT news and updates,
                    including our associated mobile applications (Mobile Apps) owned and controlled by Reconnaissance Technologies.
                    This Privacy Policy governs our data collection, processing and usage practices. It also describes your choices regarding use, access and correction
                    of your personal information. If you do not agree with the data practices described in this Privacy Policy, you should not use the Websites or the Subscription Service.
                </p>

                <p class="pb-6">
                    This legal document is an electronic record in terms of Nigeria's Data Protection Act, 2023, and rules there under as applicable and the amended provisions pertaining to electronic records
                    in various statutes as amended by the Nigeria Data Protection Act, 2023. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>

                <p class="pb-6">
                    This privacy policy applies to all users and subscribers of our websites.
                </p>

                <p class="pb-6">
                    By using this website, or completing the contact registration process through offline mode, you agree and acknowledge that you have carefully read this privacy policy and accepted this agreement.
                </p>

                <p class="pb-6">
                    References in these Terms to "we" or "us" or “website” or “company” or “Reconnaissance Technologies” are references to www.reconnaissancetechnologies.com and “you” as subscriber/user of a website.
                </p>

                <h1 class="w-full text-xl lg:text-4xl font-bold mt-2 mb-2 lg:mb-3">
                    Preamble
                </h1>
                <p class="pb-6">
                    While providing information for various web development services, the issue of online privacy is extremely crucial to Reconnaissance Technologies, which is committed for safeguarding the information provided by its users. We are dedicated to create a reasonably secured environment for our users.
                </p>

                <p class="pb-6">
                    Respecting privacy of its online users while providing top-of-the-line services have always been the core strategies of Reconnaissance Technologies. Our Privacy Policy gives users a view of the Privacy Practices followed by us and assures them of safe passage through the website.
                </p>

                <p class="pb-6">
                    At the same time, we would like to make it clear that our website may provide links to other websites/apps that are governed by their own Privacy Policies and we do not take responsibility for the security and privacy provided by these sites/apps. This may include but are not limited to payment gateway sites. Users are urged to familiarize themselves with its Privacy Policy as well the policies of the third party sites/apps that collect personally identifiable information.
                </p>

                <p class="pb-6">
                    When you provide us with your personal data, you are agreeing to the rules and regulations stipulated under our Privacy Policy and are bound by it. If you do not agree to our Policy then please do not use our website.
                </p>

                <h1 class="w-full text-xl lg:text-4xl font-bold mt-2 mb-2 lg:mb-3">
                    The Privacy Policy Shall be Governed in These Areas
                </h1>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    1. Collection of Personal Information
                </h1>

                We may collect personal information from you when you visit our website, register an account, use our services, or communicate with us. The types of personal information we may collect include:
                <br>

                <ul class="ml-10 p-5 list-disc">
                    <li>Name</li>
                    <li>Email Address</li>
                    <li>Phone Number</li>
                    <li>Address</li>
                    <li>Payment Information</li>
                </ul>
                </p>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    2. Use of Personal Information
                </h1>

                We may use your personal information for the following purposes:

                <ul class="ml-10 p-5 list-disc">
                    <li>To provide our services to you</li>
                    <li>To communicate with you about our services</li>
                    <li>To process payments</li>
                    <li>To improve our services</li>
                    <li>To comply with legal obligations</li>
                </ul>
                </p>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    3. Disclosure of Personal Information
                </h1>

                We may disclose your personal information to third parties in the following circumstances:

                <ul class="ml-10 p-5 list-disc">
                    <li>With your consent</li>
                    <li>To comply with legal obligations</li>
                    <li>To protect our rights or property</li>
                    <li>To third-party service providers who help us provide our services</li>
                </ul>
                </p>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    4. Data Security
                </h1>

                We take reasonable measures to protect your personal information from unauthorized access, disclosure, alteration, or destruction.
                However, no method of transmission over the internet or electronic storage is 100% secure, and we cannot guarantee its absolute security.
                </p>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    5. Your Rights
                </h1>

                You have the right to access, correct, or delete your personal information. You may also have other rights under applicable data protection laws.
                </p>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    6. Changes to this Privacy Policy
                </h1>

                We may update this Privacy Policy from time to time. Any changes will be effective when we post the revised policy on our website.
                </p>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    7. Contact Us
                </h1>

                If you have any questions about this Privacy Policy, please contact us at <a class="text-blue" href="mailto:dataprotection@reconnaissancetechnologies.com">dataprotection@reconnaissancetechnologies.com</a>
                </p>

                <p class="pb-6">
                <h1 class="w-full text-xl lg:text-xl font-bold mt-2 mb-2">
                    Legal Basis for Processing Personal Information
                </h1>

                The legal basis for processing your personal information is based on Nigeria's Data Protection Regulations, which require us to obtain your consent before collecting or using your personal information for specified purposes.
                </p>
            </div>
        </div>
    </section>
    <!-- End of Privacy Policy Statement Section -->

    <!-- Banner CTA Section -->
    <section class=" h-80 px-16 bg-black text-white flex justify-between items-center">
        <div class="w-3/4 py-6">
            <h1 class="text-xl lg:text-4xl font-bold mt-2 mb-2 lg:mb-6">
                Transform Your Business
            </h1>
            <p>
                Experience the power of technology as we leverage on it to build solutions that stands the test of time
            </p>
        </div>

        <a href="{{ route('contact-us') }}" class="text-white border bg-blue-600 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2 dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-500 dark:focus:ring-blue-800">
            Speak with an Expert
        </a>
    </section>
    <!-- End of Banner CTA Section -->

    <!-- Locations & Enquiry Section -->
    <section class="w-[1440px] h-[684px] pl-[50px] pr-[104px] py-[91px] bg-[#EDEDF8] justify-start items-center inline-flex">
        <div class="py-6">
            <div class="px-16 ">
                <h2 class="text-[#424d57] text-xl pb-5 uppercase font-semibold">GET IN TOUCH</h2>
                <h1 class="w-3/4 text-xl lg:text-2xl font-bold mt-2 mb-2 lg:mb-3 text-[#292D32] whitespace-nowrap">
                    Let's build something magical <br> together!
                </h1>
            </div>
            <div class="relative h-96 py-6 bg-center bg-no-repeat bg-blend-multiply">
                <p class="pl-16 text-md text-[#424d57] font-normal ">Do you have an app idea and need to get it validated? Let us give you <br> our honest opinion</p>
                <div class="flex pt-6 pl-16 text-white">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
                    </svg>
                    <div class="pl-3 text-[#424d57]">
                        <p class="text-xl font-medium whitespace-nowrap">
                            No 50, Ebitu Ukiwe Street, Jabi, Abuja - 900108, FCT
                        </p>
                    </div>
                </div>

                <div class="flex py-3 text-[#424d57] pl-16">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 6.75c0 8.284 6.716 15 15 15h2.25a2.25 2.25 0 002.25-2.25v-1.372c0-.516-.351-.966-.852-1.091l-4.423-1.106c-.44-.11-.902.055-1.173.417l-.97 1.293c-.282.376-.769.542-1.21.38a12.035 12.035 0 01-7.143-7.143c-.162-.441.004-.928.38-1.21l1.293-.97c.363-.271.527-.734.417-1.173L6.963 3.102a1.125 1.125 0 00-1.091-.852H4.5A2.25 2.25 0 002.25 4.5v2.25z" />
                    </svg>
                    <div class="pl-3 ">
                        <p class="text-xl font-medium">
                            <a href="tel:+2342013309246" title="Call Reconnaissance Technologies Nigeria">+234 201 330 9246</a>
                        </p>
                    </div>
                </div>

                <div class="flex text-[#424d57] pl-16 rounded-lg">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M21.75 6.75v10.5a2.25 2.25 0 01-2.25 2.25h-15a2.25 2.25 0 01-2.25-2.25V6.75m19.5 0A2.25 2.25 0 0019.5 4.5h-15a2.25 2.25 0 00-2.25 2.25m19.5 0v.243a2.25 2.25 0 01-1.07 1.916l-7.5 4.615a2.25 2.25 0 01-2.36 0L3.32 8.91a2.25 2.25 0 01-1.07-1.916V6.75" />
                    </svg>
                    <div class="pl-3 ">
                        <p class="text-xl font-medium">
                            <a href="mailto:enquiries@reconnaissancetechnologies.com" title="Email Reconnaissance Technologies for enquiries">enquiries@reconnaissancetechnologies.com</a>
                        </p>
                    </div>
                </div>

                <div class="absolute lg:w-[500px] xl:w-[500px] 2xl:w-[500px] left-[650px] -top-28 p-4 bg-rt-primary border-gray-200 rounded-lg shadow-lg sm:p-6 md:p-8">
                    <!-- <h3 class="text-black mb-6 text-xl font-semibold">Hola :)</h3> -->
                    @include('inc.get-a-quote-form')
                </div>
            </div>
        </div>
    </section>
    <!-- End of Locations & Enquiry Section -->
</main>
@endsection